### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by sundrb** [Bishalsarang/Pearson-PDF-Downloader#1]
![image](https://user-images.githubusercontent.com/55596936/80138139-fabb9080-85c1-11ea-9ccb-38234d4f758e.png)

**Comment by Bishalsarang** [comment]
I think you forgot to install the dependencies. Try
`pip install -r requirements.txt`
before running
`python pdl.py`

**Comment by sundrb** [comment]
Can you help me get this book pls
https://www.pearson.com/us/higher-education/product/Chopra-Instructor-s-Solutions-Manual-Download-only-for-Supply-Chain-Management-Strategy-Planning-and-Operation-6th-Edition/9780133800616.html

**Comment by Bishalsarang** [comment]
I don't have access to the Pearson instructor account. My trial account has global and sixth edition book only.
If you happen to have an instructor account you can grab..
